### ISSUE TITLE
Nothing gets printed, QR code blank

### ISSUE THREAD

**Issue by matixmatix** [jabbrwcky/prawn-qrcode#13]
I'm using prawn 1.3.0 and prawn-qrcode 0.2.2.1 and when I want to print a sample QR code:

``` ruby
qrcode = RQRCode::QRCode.new 'https://github.com/jabbrwcky/prawn-qrcode', :size=>5
text "QR code start"
render_qr_code(qrcode)
text "QR code end"
```

Only "QR code start" and "QR code end" strings get printed, and no actual QR code in between. What could be the reason?

**Comment by jabbrwcky** [comment]
Sorry, it took me a while to find some time for this project again.
Seems like some subtle changes in Prawn since 0.11.1.

Also did some cleanup (like requiring ruby >2 and Prawn >1) so everything should be back to normal now.
